- name: Configure Proxmox Hosts
  hosts: proxmox
  become: true
  roles:
    - role: proxmox_base
    - role: proxmox_firewall
    - role: proxmox_fail2ban
    - role: proxmox_acme

- name: Configure Work Station VM
  hosts: work_station
  become: true
  roles:
    - role: work_station
